// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AeroHubBlazorServer.Models
{
    public partial class MetaData
    {
        [Required]
        [Unicode(false)]
        public string FileName { get; set; }
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string DocumentType { get; set; }
        public int FeatureItemids { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string PartNumber { get; set; }
        [Required]
        [Unicode(false)]
        public string FileLink { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string User { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTime { get; set; }
        public bool Signatures { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string SupplierName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string ProcessNumber { get; set; }
        public Guid QPID { get; set; }

        [ForeignKey("QPID")]
        [InverseProperty("MetaData")]
        public virtual QIFDocument QP { get; set; }
    }
}