// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AeroHubBlazorServer.Models
{
    public partial class QIFDocument
    {
        public QIFDocument()
        {
            MetaData = new HashSet<MetaData>();
        }

        [Key]
        public Guid QPID { get; set; }
        public int IDMax { get; set; }
        [Required]
        [Column(TypeName = "xml")]
        public string MBD { get; set; }

        [InverseProperty("QP")]
        public virtual ICollection<MetaData> MetaData { get; set; }
    }
}