// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AeroHubBlazorServer.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AeroHubBlazorServer.DbContexts
{
    public partial class MFINContext
    {
        private MFINContextProcedures _procedures;

        public virtual MFINContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MFINContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public MFINContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<InsertNewQIFResult>().HasNoKey().ToView(null);
        }
    }

    public interface IMFINContextProcedures
    {
        Task<List<InsertNewQIFResult>> InsertNewQIFAsync(Guid? QPID, int? IDMax, string MBDFILE, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }

    public partial class MFINContextProcedures : IMFINContextProcedures
    {
        private readonly MFINContext _context;

        public MFINContextProcedures(MFINContext context)
        {
            _context = context;
        }

        public virtual async Task<List<InsertNewQIFResult>> InsertNewQIFAsync(Guid? QPID, int? IDMax, string MBDFILE, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "QPID",
                    Value = QPID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "IDMax",
                    Value = IDMax ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MBDFILE",
                    Size = 1,
                    Value = MBDFILE ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<InsertNewQIFResult>("EXEC @returnValue = [dbo].[InsertNewQIF] @QPID, @IDMax, @MBDFILE", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
